
clear all
clc 
N=100000; % Number of points
B = 0.0005; % Separation between the two plates in m
Vlp = -10; % Velocity of the lower plate (for part b) 
density = 1.26e3; % Fluid density in kg/m^3
u = 1.412; % Fluid viscosity in Pa*s
dp = -200*10^6; %Pa/m
dy=B/(N+1); %number of chunks 

%For part A:

%A is an N*N matrix with 2 on the diagonal, -1  on the subdiagonal and
%superdiagonal. A is the left hand side of the grid point i. 
%A is generated by using a function uploaded on Mathworks File Exchange by
%John D'Errico
%https://www.mathworks.com/matlabcentral/fileexchange/10603--block--tri-diagonal-matrices/content/BLKTRIDIAG/demo/html/blktridiag_demo.html
%Note: I have emailed Dr.Walker about using this and she said it is fine 
A = blktridiag(2,-1,-1,N);

for i=1:1:N; 
%Genrate the right hand side of the grid point i. 
   G(i)=-(dy^2*dp/u);
end
%Calculate the velocities at differenet y values 
 Va=A\G';
 
 
%Similarly, for part b: 
A = blktridiag(2,-1,-1,N);
for i=1:1:N;  
   G(i)=-(dy^2*dp/u);
end
%Here, we need to add the the velocity of the lower plate to the first term
%of G as at y=0 V=Vlp= -10
M=G(1)+Vlp;
G(1)=M;
%Calculate the velocity
Vb=A\G';

%The y values are needed to plot the velocity. The values range from 0 to B. 
Y=linspace(0,B,N); 
plot(Va, Y, '-r', Vb, Y,'-.b')
xlabel('V (m/s)')
ylabel('Y (m)')
title('The separation between the plates Y vs the velocity V')
legend('Part A', 'Part B')

